Repository codeit-bootcamp-spring/1-sprint-mission, pull requests merged in 2025-02, with the labels that each got.

#131 [ 김효정 ] sprint2
  build.gradle
  checkstyle.xml
  data/channel.ser
  savedata/channel.ser
  savedata/message.ser
  savedata/user.ser
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessagelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserlRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/util/DateUtils.java
Labels: 지각제출⏰

#92 [이원길] sprint2
  .gitignore
  build.gradle
  channel.ser
  message.ser
  src/main/java/com/sprint/mission/discodeit/AppConfig.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/exception/channel/ChannelNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/exception/channel/IllegalChannelException.java
  src/main/java/com/sprint/mission/discodeit/exception/message/MessageNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/exception/message/NullMessageContentException.java
  src/main/java/com/sprint/mission/discodeit/exception/message/NullMessageTitleException.java
  src/main/java/com/sprint/mission/discodeit/exception/user/IllegalUserException.java
  src/main/java/com/sprint/mission/discodeit/exception/user/UserNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/factory/AppConfig.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/service/validate/ChannelServiceValidator.java
  src/main/java/com/sprint/mission/discodeit/service/validate/FileMessageServiceValidator.java
  src/main/java/com/sprint/mission/discodeit/service/validate/MessageServiceValidator.java
  src/main/java/com/sprint/mission/discodeit/service/validate/ServiceValidator.java
  src/main/java/com/sprint/mission/discodeit/service/validate/UserServiceValidator.java
  src/test/java/com/sprint/mission/discodeit/entity/ChannelTest.java
  src/test/java/com/sprint/mission/discodeit/entity/MessageTest.java
  src/test/java/com/sprint/mission/discodeit/entity/UserTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicChannelServiceWithFileTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicChannelServiceWithJCFTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicMessageServiceWithFileTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicMessageServiceWithJCFTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceWithFileTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceWithJCFTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFChannelServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFMessageServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFUserServiceTest.java
  user.ser
Labels: 매운맛🔥

#133 [김희수] sprint2
  src/main/java/com/sprint/mission/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Entity.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileIOHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 지각제출⏰

#112 [박서연] sprint2
  README.md
  src/main/java/discodeit/JavaApplication.java
  src/main/java/discodeit/entity/Channel.java
  src/main/java/discodeit/entity/Message.java
  src/main/java/discodeit/entity/User.java
  src/main/java/discodeit/repository/ChannelRepository.java
  src/main/java/discodeit/repository/MessageRepository.java
  src/main/java/discodeit/repository/UserRepository.java
  src/main/java/discodeit/repository/file/FileChannelRepository.java
  src/main/java/discodeit/repository/file/FileMessageRepository.java
  src/main/java/discodeit/repository/file/FileUserRepository.java
  src/main/java/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/discodeit/service/ChannelService.java
  src/main/java/discodeit/service/MessageService.java
  src/main/java/discodeit/service/UserService.java
  src/main/java/discodeit/service/basic/BasicChannelService.java
  src/main/java/discodeit/service/basic/BasicMessageService.java
  src/main/java/discodeit/service/basic/BasicUserService.java
  src/main/java/discodeit/service/file/FileChannelService.java
  src/main/java/discodeit/service/file/FileMessageService.java
  src/main/java/discodeit/service/file/FileUserService.java
  src/main/java/discodeit/service/jcf/JCFChannelService.java
  src/main/java/discodeit/service/jcf/JCFMessageService.java
  src/main/java/discodeit/service/jcf/JCFServiceFactory.java
  src/main/java/discodeit/service/jcf/JCFUserService.java
  src/main/java/discodeit/validator/ChannelValidator.java
  src/main/java/discodeit/validator/MessageValidator.java
  src/main/java/discodeit/validator/UserValidator.java
  src/main/java/discodeit/validator/Validator.java
  src/test/java/ChannelTest.java
  src/test/java/MessageTest.java
  src/test/java/UserTest.java
  src/test/java/ValidatorTest.java
Labels: 매운맛🔥

#122 [오하람] sprint2
  src/main/groovy/some_path/_1sprintmission/Application.groovy
  src/main/groovy/some_path/_1sprintmission/discodeit/entiry/User.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/ChannelRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/UserRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/file/FileChannelRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/file/FileMessageRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/file/FileUserRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/MessageService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/basic/BasicUserService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/file/FileChannelService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/file/FileMessageService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/file/FileUserService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/jcf/JCFChannelService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/jcf/JCFMessageService.java
  src/main/groovy/some_path/_1sprintmission/discodeit/service/jcf/JCFUserService.java
  src/main/resources/tmp/channel.txt
  src/main/resources/tmp/message.txt
  src/main/resources/tmp/user.txt
  src/test/groovy/some_path/_1sprintmission/Channel/CreateChannel.java
  src/test/groovy/some_path/_1sprintmission/Channel/UserJoinChannel.java
  src/test/groovy/some_path/_1sprintmission/Message/CreateMessage.java
Labels: 매운맛🔥

#233 [오하람] sprint4
  src/main/groovy/some_path/_1sprintmission/Application.groovy
  src/main/groovy/some_path/_1sprintmission/discodeit/Controller/BasicAuthController.java
  src/main/groovy/some_path/_1sprintmission/discodeit/Controller/BasicChannelController.java
  src/main/groovy/some_path/_1sprintmission/discodeit/Controller/BasicMessageController.java
  src/main/groovy/some_path/_1sprintmission/discodeit/Controller/BasicUserController.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/ReadStatusRepository.java
  src/main/groovy/some_path/_1sprintmission/discodeit/repository/jcf/JCFUserRepository.java
Labels: 매운맛🔥, 미완성🛠️

#229 [김효정] sprint4
  build.gradle
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/auth/AuthUserDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/binarycontent/BinaryContentCreateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/binarycontent/BinaryContentRequestDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/ChannelCreateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/PrivateChannelCreateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/message/MessageCreateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/message/MessageUpdateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/readstatus/ReadStatusFindDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/user/UserUserStatusUpdateDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/userstatus/UserStatusUpdateDTO.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/exception/LoginFailedException.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yml
Labels: 매운맛🔥, 미완성🛠️
