Repository codeit-bootcamp-spring/1-sprint-mission, pull requests merged in 2025-03, with the labels that each got.

#294 [김상호] sprint4
  README.md
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 지각제출⏰

#334 Part2 김희수 sprint1
  api-docs.json
  build.gradle
  gradlew
  src/main/java/com/sprint/mission/discodeit/config/SwaggerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/BinaryContentApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ChannelApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ReadStatusApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CRrRqFH4.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 미완성🛠️

#318 [설유일] sprint6
  api-docs.json
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/SwaggerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/BinaryContentApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ChannelApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ReadStatusApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/base/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/base/BaseUpdatableEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/base/JpaConfig.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CRrRqFH4.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/DiscodeitApplicationTests.java
  src/test/java/com/sprint/mission/discodeit/entity/BinaryContentTest.java
Labels: 미완성🛠️

#339 [이성근] sprint6
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/LoginRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/binary_content/BinaryContentCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/ChannelDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/PrivateChannelCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/PublicChannelCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/channel/PublicChannelUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/message/MessageCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/message/MessageDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/message/MessageUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/read_status/ReadStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/read_status/ReadStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/user/UserCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/user/UserDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/user/UserUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/user_status/UserStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/user_status/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/base/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/base/BaseUpdatableEntity.java
  src/main/java/com/sprint/mission/discodeit/repository/BinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/BinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CRrRqFH4.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: 순한맛🐑, 미완성🛠️
